In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing import text, sequence
from tensorflow.keras import models, layers

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
text.one_hot("nice food", 45)

[39, 7]

In [6]:
vocabulary_size = 45

encoded_rev = [text.one_hot(rev, vocabulary_size) for rev in reviews]
encoded_rev

[[17, 14],
 [29, 43],
 [36, 12],
 [4, 32, 44],
 [43, 39, 14],
 [39, 14],
 [10, 39, 3],
 [40, 25],
 [40, 2],
 [20, 23]]

In [7]:
padding_len = 3
padding_rev = sequence.pad_sequences(encoded_rev, maxlen=padding_len, padding='post')
padding_rev

array([[17, 14,  0],
       [29, 43,  0],
       [36, 12,  0],
       [ 4, 32, 44],
       [43, 39, 14],
       [39, 14,  0],
       [10, 39,  3],
       [40, 25,  0],
       [40,  2,  0],
       [20, 23,  0]])

In [8]:
embeded_vector_size = 5

model = models.Sequential([
    layers.Embedding(vocabulary_size, embeded_vector_size, input_length=padding_len, name='embedding'),
    layers.Flatten(),
    layers.Dense(1, activation='sigmoid')
])


In [9]:
x = padding_rev
y = sentiment

In [10]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              225       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 241
Trainable params: 241
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x,y, epochs=50)

Epoch 1/50
1/1 [==============================] - 3s 3s/step - loss: 0.6818 - accuracy: 0.7000
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6798 - accuracy: 0.8000
Epoch 3/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6779 - accuracy: 0.8000
Epoch 4/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6760 - accuracy: 0.8000
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6740 - accuracy: 0.8000
Epoch 6/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6721 - accuracy: 0.8000
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6702 - accuracy: 0.8000
Epoch 8/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6683 - accuracy: 0.8000
Epoch 9/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6663 - accuracy: 0.9000
Epoch 10/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6644 - accuracy: 0.9000
Epoch 11/50
1/1 [======================

In [13]:
loss, accuracy = model.evaluate(x,y)
accuracy*100

1/1 [==============================] - 0s 252ms/step - loss: 0.5815 - accuracy: 1.0000


100.0

In [18]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

45

In [19]:
weights[17]

array([ 0.05682321, -0.08445043, -0.03557641,  0.07243434,  0.05149219],
      dtype=float32)

In [20]:
weights[29]

array([ 0.04433186, -0.01278708, -0.02667108,  0.05958664,  0.03458984],
      dtype=float32)